### ISSUE TITLE
NOT SAFE DON'T USE https://www.virustotal.com/gui/file/86f38aab34154bdcdcc44689f3dff8c50aa943531ae75a53a237b277e9a4d16c/details

### ISSUE THREAD

**Issue by Pickymarker** [scythe-project/BetterDiscord-Plus#2]
NOT SAFE DON'T USE https://www.virustotal.com/gui/file/86f38aab34154bdcdcc44689f3dff8c50aa943531ae75a53a237b277e9a4d16c/details

**Comment by Pickymarker** [comment]
an if this issue gets closed then you just try to hide the fact the virus total lights up from the exe

**Comment by scythe-project** [comment]
> an if this issue gets closed then you're just trying to hide the fact that virus total has 19 detections form the exe

[REPLY] You're being such a child. 😂
It's an empty EXE file with a few lines of batch scripting just to show the message it does, lol. Not my fault that the EXE builder I use causes false positives. So, instead of trying to cause trouble for me and make this repo look bad, give it a second thought before you start slandering stuff. Especially something that's less than 100KB in size. 💀

**Comment by Pickymarker** [comment]
Okay make a video
